### ISSUE TITLE
upgrade all stats of item

### ISSUE THREAD

**Issue by siriusty1** [silviu20092/azerothcore-item-upgrades#1]
I understand that in your design, only one stat can be selected for each upgrade. If I want to upgrade all the stats by 5% of an item in one upgrade, how can I do it?

**Comment by silviu20092** [comment]
You mean as a shortcut so you don't have to do extra few clicks? I didn't really think about this to be honest, since I wanted to have more control over each rank upgrade (show percentage increases, show all requirements for the rank). Obviously bulk upgrade can be done, maybe could be a feature for future ;)

**Comment by silviu20092** [comment]
Added this functionality in https://github.com/silviu20092/azerothcore-item-upgrades/commit/1ace74d2ed293ebafcf57e45a64cf3032445df22
